include <Gilgahedron.scad>
Text0 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$EOO#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text1 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$hIIIIIIIIII+O$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text2 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$####$$$$$$$$$$hIIIIIIIIIIIIIIIIE$$$$$$$$$####$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text3 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$O+IIIIIIII+E$$$$$$$$IIIIIIIIIIIIIIIIIIh$$$$$$$$HIIIIIIIIIIh#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text4 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$hIIIIIIIIIIIIIIIIH$$$$$$OIIIIIIIIIIIIIIIIIIII#$$$$$$+IIIIIIIIIIIIIIIIE$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text5 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$#IIIIIIIIIIIIIIIIIIIIH$$$$EIIIIIIIIIIIIIIIIIIIIII+$$$$#+IIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text6 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$#IIIIIIIIIIIIIIIIIIIIII+HOhIIIIIIIIIIIIIIIIIIIIIIIIIIIIHOhIIIIIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text7 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text8 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text9 = "$$$$$$$$$$$$$$$#H+II+HE$$$$$#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$$OhIIIIhO$$$$$$$$$$$$$$$$";
Text10 = "$$$$$$$$$$$$$$EIIIIIIIIIIIIII+O##O+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHE#EHIIIIIIIIIIIIIIh#$$$$$$$$$$$$$$";
Text11 = "$$$$$$$$$$$$$#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+$$$$$$$$$$$$$$";
Text12 = "$$$$$$$$$$$$$HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#$$$$$$$$$$$$$";
Text13 = "$$$$$$$$$$$$$#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$";
Text14 = "$$$$$$$$$$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+#$$$$$$$$$$$$$$";
Text15 = "$$$$$$$$$$$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#$$$$$$$$$$$$$$$";
Text16 = "$$$$$$$$$$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$";
Text17 = "$$$$$$$$$$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIH$$$$$$$$$$$$$$$$";
Text18 = "$$$$$$$EEEE#$#O+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHE$$#EEE#$$$$$$$";
Text19 = "$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+HOE######OOH+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh#$$$$$";
Text20 = "$$$$EIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+HE$$$$$$$$$$$$$$$$OhIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+$$$$$";
Text21 = "$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIhE$$$$$$$$$$$$$$$$$$$$$$O+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$";
Text22 = "$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh#$$$$$$$$$$$$$$$$$$$$$$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIH$$$$";
Text23 = "$$$$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$$$$";
Text24 = "$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$EhIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh#$$$$$";
Text25 = "$$$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#Hh++++++++++++++++++hHE$$$$$$$$";
Text26 = "$$$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text27 = "$$$$$$$$$EIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text28 = "$$$$$$$$$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text29 = "$$$$$$#O+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text30 = "$$#HhIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII$$$$$$$$$$$$$$$$$$$$$$$$$$$$$EHhhh+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIhhE$$$";
Text31 = "$EIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+$$";
Text32 = "$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$EIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$";
Text33 = "#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$";
Text34 = "$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$";
Text35 = "$#+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+$$$$$$$$$$$$$$$$$$$$$$$$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$";
Text36 = "$$$EOh+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$EOOHhhIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+HO#$$$";
Text37 = "$$$$$$$#HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+O$$$$$$$$";
Text38 = "$$$$$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#$$$$$$$$$";
Text39 = "$$$$$$$$$OIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIH$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+$$$$$$$$$$";
Text40 = "$$$$$$$$EIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$$$$$";
Text41 = "$$$$$$EhIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIH#$$$$$$";
Text42 = "$$$$#hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$";
Text43 = "$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$$$E+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$";
Text44 = "$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$$$$$$$$$$#hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIH$$$$";
Text45 = "$$$$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+H#$$$$$$$$$$$$$$$$$$$$EhIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$";
Text46 = "$$$$#IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+H#$$$$$$$$$$$$$$EhIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIh$$$$$";
Text47 = "$$$$$#hIIIIIIII+++IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+hHOOOOOOhh+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+++IIIIIIIIH$$$$$$";
Text48 = "$$$$$$$$$$$$$$#HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$$$$$$$$$$$$$$$";
Text49 = "$$$$$$$$$$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$$$$$$$$$$$";
Text50 = "$$$$$$$$$$$$$$$$IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIH$$$$$$$$$$$$$$$$";
Text51 = "$$$$$$$$$$$$$$$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$$$$$$$$$$$$$$$";
Text52 = "$$$$$$$$$$$$$$HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#$$$$$$$$$$$$$$";
Text53 = "$$$$$$$$$$$$$EIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+$$$$$$$$$$$$$$";
Text54 = "$$$$$$$$$$$$$HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#$$$$$$$$$$$$$";
Text55 = "$$$$$$$$$$$$$#+IIIIIIIIIIIIIIIIIIII+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII+IIIIIIIIIIIIIIIIIIIIH$$$$$$$$$$$$$$";
Text56 = "$$$$$$$$$$$$$$#hIIIIIIIIIIIIH#$$#HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$$$EhIIIIIIIIIIIIH$$$$$$$$$$$$$$$";
Text57 = "$$$$$$$$$$$$$$$$EHhHE$$$$$$$+IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIO$$$$$$#OhhO#$$$$$$$$$$$$$$$$";
Text58 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$hIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIE$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text59 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIH$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text60 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$#IIIIIIIIIIIIIIIIIIIIIIhE#O+IIIIIIIIIIIIIIIIIIIIIIIIhE#O+IIIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text61 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$IIIIIIIIIIIIIIIIIIIIE$$$$$+IIIIIIIIIIIIIIIIIIIIH$$$$$hIIIIIIIIIIIIIIIIIIh$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text62 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$OIIIIIIIIIIIIIIIIE$$$$$$EIIIIIIIIIIIIIIIIIIII$$$$$$$HIIIIIIIIIIIIII+#$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text63 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#H+IIIIIIh#$$$$$$$$IIIIIIIIIIIIIIIIIIH$$$$$$$$E+IIIIIIhO$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text64 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$OIIIIIIIIIIIIIIII#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text65 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$OhIIIIII+H#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
Text66 = "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
lineDist = -20;
extrudeHeight=10;
translate([0,lineDist*1,0]) text_extrude(Text1,extrudeHeight);
translate([0,lineDist*2,0]) text_extrude(Text2,extrudeHeight);
translate([0,lineDist*3,0]) text_extrude(Text3,extrudeHeight);
translate([0,lineDist*4,0]) text_extrude(Text4,extrudeHeight);
translate([0,lineDist*5,0]) text_extrude(Text5,extrudeHeight);
translate([0,lineDist*6,0]) text_extrude(Text6,extrudeHeight);
translate([0,lineDist*7,0]) text_extrude(Text7,extrudeHeight);
translate([0,lineDist*8,0]) text_extrude(Text8,extrudeHeight);
translate([0,lineDist*9,0]) text_extrude(Text9,extrudeHeight);
translate([0,lineDist*10,0]) text_extrude(Text10,extrudeHeight);
translate([0,lineDist*11,0]) text_extrude(Text11,extrudeHeight);
translate([0,lineDist*12,0]) text_extrude(Text12,extrudeHeight);
translate([0,lineDist*13,0]) text_extrude(Text13,extrudeHeight);
translate([0,lineDist*14,0]) text_extrude(Text14,extrudeHeight);
translate([0,lineDist*15,0]) text_extrude(Text15,extrudeHeight);
translate([0,lineDist*16,0]) text_extrude(Text16,extrudeHeight);
translate([0,lineDist*17,0]) text_extrude(Text17,extrudeHeight);
translate([0,lineDist*18,0]) text_extrude(Text18,extrudeHeight);
translate([0,lineDist*19,0]) text_extrude(Text19,extrudeHeight);
translate([0,lineDist*20,0]) text_extrude(Text20,extrudeHeight);
translate([0,lineDist*21,0]) text_extrude(Text21,extrudeHeight);
translate([0,lineDist*22,0]) text_extrude(Text22,extrudeHeight);
translate([0,lineDist*23,0]) text_extrude(Text23,extrudeHeight);
translate([0,lineDist*24,0]) text_extrude(Text24,extrudeHeight);
translate([0,lineDist*25,0]) text_extrude(Text25,extrudeHeight);
translate([0,lineDist*26,0]) text_extrude(Text26,extrudeHeight);
translate([0,lineDist*27,0]) text_extrude(Text27,extrudeHeight);
translate([0,lineDist*28,0]) text_extrude(Text28,extrudeHeight);
translate([0,lineDist*29,0]) text_extrude(Text29,extrudeHeight);
translate([0,lineDist*30,0]) text_extrude(Text30,extrudeHeight);
translate([0,lineDist*31,0]) text_extrude(Text31,extrudeHeight);
translate([0,lineDist*32,0]) text_extrude(Text32,extrudeHeight);
translate([0,lineDist*33,0]) text_extrude(Text33,extrudeHeight);
translate([0,lineDist*34,0]) text_extrude(Text34,extrudeHeight);
translate([0,lineDist*35,0]) text_extrude(Text35,extrudeHeight);
translate([0,lineDist*36,0]) text_extrude(Text36,extrudeHeight);
translate([0,lineDist*37,0]) text_extrude(Text37,extrudeHeight);
translate([0,lineDist*38,0]) text_extrude(Text38,extrudeHeight);
translate([0,lineDist*39,0]) text_extrude(Text39,extrudeHeight);
translate([0,lineDist*40,0]) text_extrude(Text40,extrudeHeight);
translate([0,lineDist*41,0]) text_extrude(Text41,extrudeHeight);
translate([0,lineDist*42,0]) text_extrude(Text42,extrudeHeight);
translate([0,lineDist*43,0]) text_extrude(Text43,extrudeHeight);
translate([0,lineDist*44,0]) text_extrude(Text44,extrudeHeight);
translate([0,lineDist*45,0]) text_extrude(Text45,extrudeHeight);
translate([0,lineDist*46,0]) text_extrude(Text46,extrudeHeight);
translate([0,lineDist*47,0]) text_extrude(Text47,extrudeHeight);
translate([0,lineDist*48,0]) text_extrude(Text48,extrudeHeight);
translate([0,lineDist*49,0]) text_extrude(Text49,extrudeHeight);
translate([0,lineDist*50,0]) text_extrude(Text50,extrudeHeight);
translate([0,lineDist*51,0]) text_extrude(Text51,extrudeHeight);
translate([0,lineDist*52,0]) text_extrude(Text52,extrudeHeight);
translate([0,lineDist*53,0]) text_extrude(Text53,extrudeHeight);
translate([0,lineDist*54,0]) text_extrude(Text54,extrudeHeight);
translate([0,lineDist*55,0]) text_extrude(Text55,extrudeHeight);
translate([0,lineDist*56,0]) text_extrude(Text56,extrudeHeight);
translate([0,lineDist*57,0]) text_extrude(Text57,extrudeHeight);
translate([0,lineDist*58,0]) text_extrude(Text58,extrudeHeight);
translate([0,lineDist*59,0]) text_extrude(Text59,extrudeHeight);
translate([0,lineDist*60,0]) text_extrude(Text60,extrudeHeight);
translate([0,lineDist*61,0]) text_extrude(Text61,extrudeHeight);
translate([0,lineDist*62,0]) text_extrude(Text62,extrudeHeight);
translate([0,lineDist*63,0]) text_extrude(Text63,extrudeHeight);
translate([0,lineDist*64,0]) text_extrude(Text64,extrudeHeight);
translate([0,lineDist*65,0]) text_extrude(Text65,extrudeHeight);
translate([0,lineDist*66,0]) text_extrude(Text66,extrudeHeight);
